### PR TITLE
use rust compiler spec for cross compilation

### PR DESCRIPTION
**Pull request by msarahan**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by isuruf** [comment]
@conda-forge-admin, rerender

**Comment by msarahan** [comment]
@isuruf thanks for looking at this. the current issue on the osx-arm64 build is this:

` = note: "arm64-apple-darwin20.0.0-clang" "-Wl,-exported_symbols_list,/tmp/rustc35SSfK/list" "-arch" "arm64" "/Users/runner/miniforge3/conda-bld/deno_1660072979833/work/target/aarch64-apple-darwin/release/deps/test_ffi.std-0dd069df8d91d43f.std.a06723d8-cgu.0.rcgu.o.rcgu.o" "-L" "/Users/runner/miniforge3/conda-bld/deno_1660072979833/work/target/aarch64-apple-darwin/release/deps" "-L" "/Users/runner/miniforge3/conda-bld/deno_1660072979833/work/target/release/deps" "-L" "/Users/runner/miniforge3/conda-bld/deno_1660072979833/_build_env/lib/rustlib/aarch64-apple-darwin/lib" "/Users/runner/miniforge3/conda-bld/deno_1660072979833/_build_env/lib/rustlib/aarch64-apple-darwin/lib/libcompiler_builtins-4014697324d67e93.rlib" "-lSystem" "-lresolv" "-lc" "-lm" "-liconv" "-L" "/Users/runner/miniforge3/conda-bld/deno_1660072979833/_build_env/lib/rustlib/aarch64-apple-darwin/lib" "-o" "/Users/runner/miniforge3/conda-bld/deno_1660072979833/work/target/aarch64-apple-darwin/release/deps/libtest_ffi.dylib" "-Wl,-dead_strip" "-dynamiclib" "-Wl,-dylib" "-nodefaultlibs" "-fuse-ld=lld"
  = note: clang-14: error: invalid linker name in argument '-fuse-ld=lld'`

My searching on google seems to indicate that this may be a missing part of our LLVM build (i.e. the fix is to install LLVM from home-brew). Do you know more about how to resolve this?

**Comment by msarahan** [comment]
Doing something squirrelly with the linker:

```
error: linking with `/Users/runner/miniforge3/conda-bld/deno_1660081074051/_build_env/bin/x86_64-apple-darwin13.4.0-clang` failed: exit status: 1 
...
          ld: symbol(s) not found for architecture x86_64
          clang-14: error: linker command failed with exit code 1 (use -v to see invocation)
```

`x86_64-apple-darwin13.4.0-clang` is CC_FOR_BUILD, and CC for native looks fine. Is this a bug in the rust build stuff, or in our cross compiling stuff? It seems like ld should not be looking for symbols for x86_64 here - any symbols that we are emitting should be arm64, right?

**Comment by isuruf** [comment]
> It seems like ld should not be looking for symbols for x86_64 here 

Some rust packages need to build a native exectuable (x86_64) first which is used for the host platform (arm64).

**Pull request merged**
